version: '3.7'

services:
  postgres:
    env_file: ./.env
    build:
      context: containers/pgvector
    image: oci.local/postgresql/pgvector:dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-backstage}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_backstage}
      POSTGRES_POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-postgres_admin}
      POSTGRES_REPLICATION_PASSWORD: ${POSTGRES_REPLICATION_PASSWORD:-postgre_replication}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432
    volumes: 
      - backstage-postgres:/var/lib/postgresql/data
      # - ./hack/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  backstage-postgres:
    driver: local