stages:
  - env-creation
  - prepare-${{values.awsEnvironmentName}}-stage
  - ${{values.awsEnvironmentName}}-stage

variables:
  APP_SHORT_NAME: "${{ values.component_id }}"
  APP_TEMPLATE_NAME: "example-tf-nodejs"
  OPA_PLATFORM_REGION: "${{ values.platformRegion }}"

include:
  - project: 'alithya-csna/cloud/aws/software-templates'
    ref: integrate-opa-templates 
    file:
      - 'opa-scaffolder-templates/common/cicd/.gitlab-ci-job-defaults-tf.yml'
      - 'common/cicd/.gitlab-ci-aws-base.yml'
      - 'common/cicd/.gitlab-ci-aws-tf-base.yml'
      - 'common/cicd/.gitlab-ci-aws-iac-tf-ecs.yml'
      - 'common/cicd/.gitlab-ci-aws-image-kaniko.yml'
      - 'common/cicd/.gitlab-ci-aws-image-deploy.yml'
