app:
  title: "Scaffolded Backstage App"
  baseUrl: ${APP_BASE_URL}
  listen:
    port: 3000
    host: 0.0.0.0
organization:
  name: ${ORGANIZATION_NAME}

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    host: 0.0.0.0
    port: ${BACKEND_PORT}
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${BACKEND_CORS_ORIGIN}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: ${BACKEND_DATABASE_CLIENT}
    connection: ${BACKEND_DATABASE_CONNECTION}
  platformRegion: ${BACKEND_PLATFORM_REGION}
integrations:
  github:
    - host: github.com
      apps:
        - appId: ${GITHUB_APP_ID}
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          webhookSecret: ${GITHUB_WEBHOOK_SECRET}
          privateKey: ${GITHUB_PRIVATE_KEY}


proxy:
techdocs:
  builder: ${TECHDOCS_BUILDER}
  generator:
    runIn: ${TECHDOCS_GENERATOR_RUN_IN}
  publisher:
    type: ${TECHDOCS_PUBLISHER_TYPE} #

auth:
  environment: ${AUTH_ENVIRONMENT}
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: ${AUTH_PROVIDERS_GUEST_DANGEROUSLY_ALLOW_OUTSIDE_DEVELOPMENT}
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

scaffolder:
catalog:
  rules:
    - allow:
        [
          Domain,
          Component,
          System,
          API,
          Resource,
          Location,
          Template,
          AWSEnvironment,
          AWSEnvironmentProvider,
        ]
  providers:
    githubOrg:
      - id: default
        githubUrl: https://github.com
        orgs:
          - harmonix-generated-environments
        schedule:
          frequency: PT30M
          timeout: PT1M
  orphanStrategy: delete
  processingInterval:
    minutes: 10
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  locations:
    - type: url
      target: https://github.com/harmonix-generated-environments/harmonix/blob/integrate-github-ref/backstage-reference/templates/all-templates.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/landing-zone-accelerator/*
      rules:
        - allow: [Component, System]

kubernetes:
  # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: ${PERMISSION_ENABLED}

aws:
  accountDefaults:
    roleName: ${AWS_ACCOUNT_DEFAULTS_ROLE_NAME}
    partition: ${AWS_ACCOUNT_DEFAULTS_PARTITION}
    region: ${AWS_ACCOUNT_DEFAULTS_REGION}
  mainAccount:
    accessKeyId: ${AWS_MAIN_ACCOUNT_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_MAIN_ACCOUNT_SECRET_ACCESS_KEY}
    region: ${AWS_MAIN_ACCOUNT_REGION}
  accounts:
    - accountId: "957201034306"
      roleName: ${AWS_BILLING_ACCOUNT_ROLE_NAME}
  locator:
    resourceTaggingApi:
      accounts:
        - '012345678901'
      regions:
        - us-east-1
  sso:
    subdomain: ${AWS_SSO_SUBDOMAIN}
  costInsights:
    costExplorer:
      accountId: '${AWS_COST_EXPLORER_ACCOUNT_ID}'
      region: ${AWS_COST_EXPLORER_REGION}
    cache:
      enabled: ${COST_INSIGHTS_CACHE_ENABLED}
      defaultTtl: ${COST_INSIGHTS_CACHE_DEFAULT_TTL}
      readTime: ${COST_INSIGHTS_CACHE_READ_TIME}
    entityGroups:
      - kind: Component
        groups:
          - name: service
            type: DIMENSION
            key: SERVICE
          - name: landing-zone-accelerator-cccs
            type: TAG
            key: Accelerator

costInsights:
  engineerCost: ${COST_INSIGHTS_ENGINEER_COST}