name: Automate Renovate changeset
on:
  pull_request_target:
    paths:
      - '.github/workflows/automate_renovate_changesets.yml'
      - '**/yarn.lock'

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'backstage-goalie[bot]' && github.repository == 'backstage/community-plugins'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'Github changeset workflow'

      - name: Generate feedback
        uses: backstage/actions/renovate-changesets@25145dd4117d50e1da9330e9ed2893bc6b75373e # v0.6.15
        with:
          multiple-workspaces: true
