name: PR
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issue_comment:
    types:
      - created

jobs:
  sync:
    runs-on: ubuntu-latest

    # Avoid running on issue comments
    if: github.repository == 'alithya-oss/backstage-plugins' && ( github.event.pull_request || github.event.issue.pull_request )
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: PR sync
        uses: backstage/actions/pr-sync@25145dd4117d50e1da9330e9ed2893bc6b75373e # v0.6.15
        with:
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          app-id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}
          private-key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
          installation-id: ${{ secrets.BACKSTAGE_GOALIE_INSTALLATION_ID }}
          auto-assign: false
